// <auto-generated />
using System;
using HELP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210216011345_UpdatedProject")]
    partial class UpdatedProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HELP.API.Entities.AppKyChngLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KyChngDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KyCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("KyNewChng")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KyChngz");
                });

            modelBuilder.Entity("HELP.API.Entities.AppKyFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KyFeatureDue")
                        .HasColumnType("TEXT");

                    b.Property<string>("KyFeaturePhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("KyNewFeature")
                        .HasColumnType("TEXT");

                    b.Property<string>("KyNewFeatureDetails")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KyFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
