// <auto-generated />
using HELP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210126024437_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HELP.API.Entities.AppKyChngLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KyChngDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("KyNewChng")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KyChngz");
                });
#pragma warning restore 612, 618
        }
    }
}
